(part "TNPW040236K1BEED"
    (packageRef "RESC1005X40N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "TNPW040236K1BEED")
    (property "Mouser_Part_Number" "71-TNPW040236K1BEED")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Dale/TNPW040236K1BEED?qs=acBVhj9v9XUFtfIKA92T4A%3D%3D")
    (property "Arrow_Part_Number" "TNPW040236K1BEED")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tnpw040236k1beed/vishay?utm_currency=USD&region=nac")
    (property "Description" "Res Thin Film 0402 36.1K Ohm 0.1% 0.07W +/-25ppm/C Sulfur Resistant Pad SMD T/R Medical Automotive AEC-Q200")
    (property "Datasheet_Link" "https://www.vishay.com/docs/28758/tnpw_e3.pdf")
    (property "symbolName1" "TNPW040236K1BEED")
)
